version: '3'
services:

  loadbalancer:
    image: nginx:latest
    container_name: loadbalancer_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 9090:80

  backendOneHost:
    image: nginx:latest
    container_name: backendOne_nginx
    volumes:
      - ./htmlOne:/usr/share/nginx/html

  backendOneBackupHost:
    image: nginx:latest
    container_name: backendOneBackup_nginx
    volumes:
      - ./htmlOneBackup:/usr/share/nginx/html

  backendTwoHost:
    image: nginx:latest
    container_name: backendTwo_nginx
    volumes:
      - ./htmlTwo:/usr/share/nginx/html

  backendTwoBackupHost:
    image: nginx:latest
    container_name: backendTwoBackup_nginx
    volumes:
      - ./htmlTwoBackup:/usr/share/nginx/html